
package gov.noaa.nos.coops.opendap.webservices.waterlevelverifiedsixmin;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WaterLevelVerifiedSixMinService", targetNamespace = "https://opendap.co-ops.nos.noaa.gov/axis/webservices/waterlevelverifiedsixmin/wsdl", wsdlLocation = "https://opendap.co-ops.nos.noaa.gov/axis/webservices/waterlevelverifiedsixmin/wsdl/WaterLevelVerifiedSixMin.wsdl")
public class WaterLevelVerifiedSixMinService
    extends Service
{

    private final static URL WATERLEVELVERIFIEDSIXMINSERVICE_WSDL_LOCATION;
    private final static WebServiceException WATERLEVELVERIFIEDSIXMINSERVICE_EXCEPTION;
    private final static QName WATERLEVELVERIFIEDSIXMINSERVICE_QNAME = new QName("https://opendap.co-ops.nos.noaa.gov/axis/webservices/waterlevelverifiedsixmin/wsdl", "WaterLevelVerifiedSixMinService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://opendap.co-ops.nos.noaa.gov/axis/webservices/waterlevelverifiedsixmin/wsdl/WaterLevelVerifiedSixMin.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WATERLEVELVERIFIEDSIXMINSERVICE_WSDL_LOCATION = url;
        WATERLEVELVERIFIEDSIXMINSERVICE_EXCEPTION = e;
    }

    public WaterLevelVerifiedSixMinService() {
        super(__getWsdlLocation(), WATERLEVELVERIFIEDSIXMINSERVICE_QNAME);
    }

    public WaterLevelVerifiedSixMinService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WATERLEVELVERIFIEDSIXMINSERVICE_QNAME, features);
    }

    public WaterLevelVerifiedSixMinService(URL wsdlLocation) {
        super(wsdlLocation, WATERLEVELVERIFIEDSIXMINSERVICE_QNAME);
    }

    public WaterLevelVerifiedSixMinService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WATERLEVELVERIFIEDSIXMINSERVICE_QNAME, features);
    }

    public WaterLevelVerifiedSixMinService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WaterLevelVerifiedSixMinService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WaterLevelVerifiedSixMinPortType
     */
    @WebEndpoint(name = "WaterLevelVerifiedSixMin")
    public WaterLevelVerifiedSixMinPortType getWaterLevelVerifiedSixMin() {
        return super.getPort(new QName("https://opendap.co-ops.nos.noaa.gov/axis/webservices/waterlevelverifiedsixmin/wsdl", "WaterLevelVerifiedSixMin"), WaterLevelVerifiedSixMinPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WaterLevelVerifiedSixMinPortType
     */
    @WebEndpoint(name = "WaterLevelVerifiedSixMin")
    public WaterLevelVerifiedSixMinPortType getWaterLevelVerifiedSixMin(WebServiceFeature... features) {
        return super.getPort(new QName("https://opendap.co-ops.nos.noaa.gov/axis/webservices/waterlevelverifiedsixmin/wsdl", "WaterLevelVerifiedSixMin"), WaterLevelVerifiedSixMinPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WATERLEVELVERIFIEDSIXMINSERVICE_EXCEPTION!= null) {
            throw WATERLEVELVERIFIEDSIXMINSERVICE_EXCEPTION;
        }
        return WATERLEVELVERIFIEDSIXMINSERVICE_WSDL_LOCATION;
    }

}
