
package gov.noaa.nos.coops.opendap.webservices.waterlevelverifiedsixmin;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WaterLevelVerifiedSixMinPortType", targetNamespace = "https://opendap.co-ops.nos.noaa.gov/axis/webservices/waterlevelverifiedsixmin/wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WaterLevelVerifiedSixMinPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns gov.noaa.nos.coops.opendap.webservices.waterlevelverifiedsixmin.WaterLevelVerifiedSixMinMeasurements
     */
    @WebMethod
    @WebResult(name = "WaterLevelVerifiedSixMinMeasurements", targetNamespace = "https://opendap.co-ops.nos.noaa.gov/axis/webservices/waterlevelverifiedsixmin/wsdl", partName = "WaterLevelVerifiedSixMinMeasurements")
    public WaterLevelVerifiedSixMinMeasurements getWaterLevelVerifiedSixMin(
        @WebParam(name = "Parameters", targetNamespace = "https://opendap.co-ops.nos.noaa.gov/axis/webservices/waterlevelverifiedsixmin/wsdl", partName = "Parameters")
        Parameters parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns gov.noaa.nos.coops.opendap.webservices.waterlevelverifiedsixmin.WLandMetadata
     */
    @WebMethod
    @WebResult(name = "WLandMetadata", targetNamespace = "https://opendap.co-ops.nos.noaa.gov/axis/webservices/waterlevelverifiedsixmin/wsdl", partName = "WLandMetadata")
    public WLandMetadata getWLVerifiedSixMinAndMetadata(
        @WebParam(name = "Parameters", targetNamespace = "https://opendap.co-ops.nos.noaa.gov/axis/webservices/waterlevelverifiedsixmin/wsdl", partName = "Parameters")
        Parameters parameters);

}
