
package gov.noaa.nos.coops.opendap.webservices.highlowtidepred;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "highlowtidepredService", targetNamespace = "https://opendap.co-ops.nos.noaa.gov/axis/webservices/highlowtidepred/wsdl", wsdlLocation = "https://opendap.co-ops.nos.noaa.gov/axis/webservices/highlowtidepred/wsdl/HighLowTidePred.wsdl")
public class HighlowtidepredService
    extends Service
{

    private final static URL HIGHLOWTIDEPREDSERVICE_WSDL_LOCATION;
    private final static WebServiceException HIGHLOWTIDEPREDSERVICE_EXCEPTION;
    private final static QName HIGHLOWTIDEPREDSERVICE_QNAME = new QName("https://opendap.co-ops.nos.noaa.gov/axis/webservices/highlowtidepred/wsdl", "highlowtidepredService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://opendap.co-ops.nos.noaa.gov/axis/webservices/highlowtidepred/wsdl/HighLowTidePred.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HIGHLOWTIDEPREDSERVICE_WSDL_LOCATION = url;
        HIGHLOWTIDEPREDSERVICE_EXCEPTION = e;
    }

    public HighlowtidepredService() {
        super(__getWsdlLocation(), HIGHLOWTIDEPREDSERVICE_QNAME);
    }

    public HighlowtidepredService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HIGHLOWTIDEPREDSERVICE_QNAME, features);
    }

    public HighlowtidepredService(URL wsdlLocation) {
        super(wsdlLocation, HIGHLOWTIDEPREDSERVICE_QNAME);
    }

    public HighlowtidepredService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HIGHLOWTIDEPREDSERVICE_QNAME, features);
    }

    public HighlowtidepredService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HighlowtidepredService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HighlowtidepredPortType
     */
    @WebEndpoint(name = "highlowtidepred")
    public HighlowtidepredPortType getHighlowtidepred() {
        return super.getPort(new QName("https://opendap.co-ops.nos.noaa.gov/axis/webservices/highlowtidepred/wsdl", "highlowtidepred"), HighlowtidepredPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HighlowtidepredPortType
     */
    @WebEndpoint(name = "highlowtidepred")
    public HighlowtidepredPortType getHighlowtidepred(WebServiceFeature... features) {
        return super.getPort(new QName("https://opendap.co-ops.nos.noaa.gov/axis/webservices/highlowtidepred/wsdl", "highlowtidepred"), HighlowtidepredPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HIGHLOWTIDEPREDSERVICE_EXCEPTION!= null) {
            throw HIGHLOWTIDEPREDSERVICE_EXCEPTION;
        }
        return HIGHLOWTIDEPREDSERVICE_WSDL_LOCATION;
    }

}
