
package gov.noaa.nos.coops.opendap.webservices.highlowtidepred;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "highlowtidepredPortType", targetNamespace = "https://opendap.co-ops.nos.noaa.gov/axis/webservices/highlowtidepred/wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HighlowtidepredPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns gov.noaa.nos.coops.opendap.webservices.highlowtidepred.HighLowValues
     */
    @WebMethod
    @WebResult(name = "HighLowValues", targetNamespace = "https://opendap.co-ops.nos.noaa.gov/axis/webservices/highlowtidepred/wsdl", partName = "HighLowValues")
    public HighLowValues getHighLowTidePredictions(
        @WebParam(name = "Parameters", targetNamespace = "https://opendap.co-ops.nos.noaa.gov/axis/webservices/highlowtidepred/wsdl", partName = "Parameters")
        Parameters parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns gov.noaa.nos.coops.opendap.webservices.highlowtidepred.HighLowAndMetadata
     */
    @WebMethod
    @WebResult(name = "HighLowAndMetadata", targetNamespace = "https://opendap.co-ops.nos.noaa.gov/axis/webservices/highlowtidepred/wsdl", partName = "HighLowAndMetadata")
    public HighLowAndMetadata getHLPredAndMetadata(
        @WebParam(name = "Parameters", targetNamespace = "https://opendap.co-ops.nos.noaa.gov/axis/webservices/highlowtidepred/wsdl", partName = "Parameters")
        Parameters parameters);

}
