
package gov.noaa.nos.coops.opendap.webservices.activestations;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ActiveStationsSoapPortType", targetNamespace = "https://opendap.co-ops.nos.noaa.gov/axis/webservices/activestations/wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ActiveStationsSoapPortType {


    /**
     * 
     * @return
     *     returns gov.noaa.nos.coops.opendap.webservices.activestations.ActiveStations
     */
    @WebMethod
    @WebResult(name = "ActiveStations", targetNamespace = "https://opendap.co-ops.nos.noaa.gov/axis/webservices/activestations/wsdl", partName = "ActiveStations")
    public ActiveStations getActiveStations();

    /**
     * 
     * @return
     *     returns gov.noaa.nos.coops.opendap.webservices.activestations.ActiveStationsV2
     */
    @WebMethod
    @WebResult(name = "ActiveStationsV2", targetNamespace = "https://opendap.co-ops.nos.noaa.gov/axis/webservices/activestations/wsdl", partName = "ActiveStationsV2")
    public ActiveStationsV2 getActiveStationsV2();

}
