
package gov.noaa.nos.coops.opendap.webservices.activestations;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ActiveStationsService", targetNamespace = "https://opendap.co-ops.nos.noaa.gov/axis/webservices/activestations/wsdl", wsdlLocation = "https://tides.kanga.org/wsdl/noaa-active-stations-fixed.wsdl")
public class ActiveStationsService
    extends Service
{

    private final static URL ACTIVESTATIONSSERVICE_WSDL_LOCATION;
    private final static WebServiceException ACTIVESTATIONSSERVICE_EXCEPTION;
    private final static QName ACTIVESTATIONSSERVICE_QNAME = new QName("https://opendap.co-ops.nos.noaa.gov/axis/webservices/activestations/wsdl", "ActiveStationsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://tides.kanga.org/wsdl/noaa-active-stations-fixed.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ACTIVESTATIONSSERVICE_WSDL_LOCATION = url;
        ACTIVESTATIONSSERVICE_EXCEPTION = e;
    }

    public ActiveStationsService() {
        super(__getWsdlLocation(), ACTIVESTATIONSSERVICE_QNAME);
    }

    public ActiveStationsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACTIVESTATIONSSERVICE_QNAME, features);
    }

    public ActiveStationsService(URL wsdlLocation) {
        super(wsdlLocation, ACTIVESTATIONSSERVICE_QNAME);
    }

    public ActiveStationsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACTIVESTATIONSSERVICE_QNAME, features);
    }

    public ActiveStationsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ActiveStationsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ActiveStationsSoapPortType
     */
    @WebEndpoint(name = "ActiveStations")
    public ActiveStationsSoapPortType getActiveStations() {
        return super.getPort(new QName("https://opendap.co-ops.nos.noaa.gov/axis/webservices/activestations/wsdl", "ActiveStations"), ActiveStationsSoapPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ActiveStationsSoapPortType
     */
    @WebEndpoint(name = "ActiveStations")
    public ActiveStationsSoapPortType getActiveStations(WebServiceFeature... features) {
        return super.getPort(new QName("https://opendap.co-ops.nos.noaa.gov/axis/webservices/activestations/wsdl", "ActiveStations"), ActiveStationsSoapPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACTIVESTATIONSSERVICE_EXCEPTION!= null) {
            throw ACTIVESTATIONSSERVICE_EXCEPTION;
        }
        return ACTIVESTATIONSSERVICE_WSDL_LOCATION;
    }

}
