
package gov.noaa.nos.coops.opendap.webservices.waterlevelrawsixmin;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WaterLevelRawSixMinPortType", targetNamespace = "https://opendap.co-ops.nos.noaa.gov/axis/webservices/waterlevelrawsixmin/wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WaterLevelRawSixMinPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns gov.noaa.nos.coops.opendap.webservices.waterlevelrawsixmin.WaterLevelRawSixMinMeasurements
     */
    @WebMethod
    @WebResult(name = "WaterLevelRawSixMinMeasurements", targetNamespace = "https://opendap.co-ops.nos.noaa.gov/axis/webservices/waterlevelrawsixmin/wsdl", partName = "WaterLevelRawSixMinMeasurements")
    public WaterLevelRawSixMinMeasurements getWaterLevelRawSixMin(
        @WebParam(name = "Parameters", targetNamespace = "https://opendap.co-ops.nos.noaa.gov/axis/webservices/waterlevelrawsixmin/wsdl", partName = "Parameters")
        Parameters parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns gov.noaa.nos.coops.opendap.webservices.waterlevelrawsixmin.WLandMetadata
     */
    @WebMethod
    @WebResult(name = "WLandMetadata", targetNamespace = "https://opendap.co-ops.nos.noaa.gov/axis/webservices/waterlevelrawsixmin/wsdl", partName = "WLandMetadata")
    public WLandMetadata getWLRawSixMinAndMetadata(
        @WebParam(name = "Parameters", targetNamespace = "https://opendap.co-ops.nos.noaa.gov/axis/webservices/waterlevelrawsixmin/wsdl", partName = "Parameters")
        Parameters parameters);

}
