
package gov.noaa.nos.coops.opendap.webservices.waterlevelrawsixmin;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WaterLevelRawSixMinService", targetNamespace = "https://opendap.co-ops.nos.noaa.gov/axis/webservices/waterlevelrawsixmin/wsdl", wsdlLocation = "https://opendap.co-ops.nos.noaa.gov/axis/webservices/waterlevelrawsixmin/wsdl/WaterLevelRawSixMin.wsdl")
public class WaterLevelRawSixMinService
    extends Service
{

    private final static URL WATERLEVELRAWSIXMINSERVICE_WSDL_LOCATION;
    private final static WebServiceException WATERLEVELRAWSIXMINSERVICE_EXCEPTION;
    private final static QName WATERLEVELRAWSIXMINSERVICE_QNAME = new QName("https://opendap.co-ops.nos.noaa.gov/axis/webservices/waterlevelrawsixmin/wsdl", "WaterLevelRawSixMinService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://opendap.co-ops.nos.noaa.gov/axis/webservices/waterlevelrawsixmin/wsdl/WaterLevelRawSixMin.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WATERLEVELRAWSIXMINSERVICE_WSDL_LOCATION = url;
        WATERLEVELRAWSIXMINSERVICE_EXCEPTION = e;
    }

    public WaterLevelRawSixMinService() {
        super(__getWsdlLocation(), WATERLEVELRAWSIXMINSERVICE_QNAME);
    }

    public WaterLevelRawSixMinService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WATERLEVELRAWSIXMINSERVICE_QNAME, features);
    }

    public WaterLevelRawSixMinService(URL wsdlLocation) {
        super(wsdlLocation, WATERLEVELRAWSIXMINSERVICE_QNAME);
    }

    public WaterLevelRawSixMinService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WATERLEVELRAWSIXMINSERVICE_QNAME, features);
    }

    public WaterLevelRawSixMinService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WaterLevelRawSixMinService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WaterLevelRawSixMinPortType
     */
    @WebEndpoint(name = "WaterLevelRawSixMin")
    public WaterLevelRawSixMinPortType getWaterLevelRawSixMin() {
        return super.getPort(new QName("https://opendap.co-ops.nos.noaa.gov/axis/webservices/waterlevelrawsixmin/wsdl", "WaterLevelRawSixMin"), WaterLevelRawSixMinPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WaterLevelRawSixMinPortType
     */
    @WebEndpoint(name = "WaterLevelRawSixMin")
    public WaterLevelRawSixMinPortType getWaterLevelRawSixMin(WebServiceFeature... features) {
        return super.getPort(new QName("https://opendap.co-ops.nos.noaa.gov/axis/webservices/waterlevelrawsixmin/wsdl", "WaterLevelRawSixMin"), WaterLevelRawSixMinPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WATERLEVELRAWSIXMINSERVICE_EXCEPTION!= null) {
            throw WATERLEVELRAWSIXMINSERVICE_EXCEPTION;
        }
        return WATERLEVELRAWSIXMINSERVICE_WSDL_LOCATION;
    }

}
